In [2]:
#numpy is used to work in array.the array object in numpy is called ndarray
import numpy as np
a=np.array([5,8,20,4,65],'f')#we create a numpy ndarray object by array() 
#function
b=np.array((5,8,79,2,41))
print(a)
print(b)
type(b)
a.dtype

[ 5.  8. 20.  4. 65.]
[ 5  8 79  2 41]


dtype('float32')

In [3]:
#numpy dimension
arr=np.array([[12,8,7,6],[8,3,4,6]])
print(arr)
arr.ndim #to get the number of dimension
arr[1,2] #to get a certain element from an array
#here the size of the elements in the higher dimensional array
#must be same

[[12  8  7  6]
 [ 8  3  4  6]]


4

In [4]:
#shape of array
c=np.array([[[1,8,5],[3,8,7]],[[4,6,3],[10,5,9]]])
c.shape #gives the number of 2D array and the number of 1D array
#contained by each 2D array and the number of scalars contained by each 1D
#array
c[0,1,2]
c.size #number of scalar elements contained by an array
c.nbytes

48

In [5]:
np.arange(10) # by default this function take the starting value 0
np.arange(2,10,2) #the syntax is np.arange(starting index,ending index,jump)
print(range(50)) #this does not give any list
print(list(range(5,50,6)))
np.random.permutation(np.arange(10))# permutation function rearrange 
#the elements of the list randomly
np.random.randint(45,60) #gives a random value between 45 and 60

range(0, 50)
[5, 11, 17, 23, 29, 35, 41, 47]


46

In [6]:
np.zeros(5,dtype='int') #gives an array by given shape and 
#datatype filled with zeros
#as it contains one argument it gives an one dimensional array
np.zeros((4,2),dtype='int') #it is obviously a two dimensional array

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [7]:
np.ones(8,dtype="int")
np.ones((5,7)) #by default it takes only floating values

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [8]:
A = np.random.rand(10) # By default generates random numbers b/w 0 to 1
print(A)

[0.39543721 0.52000558 0.00268972 0.78155718 0.33260228 0.18909743
 0.43347776 0.92515506 0.02611581 0.34833897]


In [9]:
c=np.random.rand(4,3) #here it gives a two dimensional array and takes random 
#value in the semi closed interval [0,1)
print(c)
c.shape #it gives the order of the matrix

[[0.73079496 0.41316116 0.71633045]
 [0.38791803 0.36993991 0.41279737]
 [0.11072657 0.45242005 0.71831399]
 [0.04352979 0.92920377 0.25419688]]


(4, 3)

In [10]:
np.arange(50).reshape(5,10) #it gives a 5 by 10 matrix between the 
#numbers 0 to 50
np.random.permutation(20).reshape(4,5)

array([[13, 18, 19,  0, 14],
       [ 1, 17,  3, 12,  6],
       [ 9, 16, 11, 10, 15],
       [ 5,  2,  8,  4,  7]])

In [11]:
a=np.arange(20)
b=a[3:11]
print(b)
b[4]=89
print(b)#for slicing the big difference between normal list and numpy array is 
#when we change any element in sliced array the same change will occur the
#main array
print(a)
idx=np.argwhere(a==89)[0][0] #here we can locate the index where the 
#changes is occured
print(idx)
a[idx]=7
print(a)

[ 3  4  5  6  7  8  9 10]
[ 3  4  5  6 89  8  9 10]
[ 0  1  2  3  4  5  6 89  8  9 10 11 12 13 14 15 16 17 18 19]
7
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
b=a[3:11].copy()#if we use the copy function then any element in a will not
#be affected by any changes of b
print(b)
#other properties are similar as list in python
a[::5]
a[::-5]
b[5]=20
print(b)
a[8] #this gives us 8 since we use copy function)

[ 3  4  5  6  7  8  9 10]
[ 3  4  5  6  7 20  9 10]


8

In [13]:
a=np.round(10*(np.random.rand(5,6)))#the round function round off the rational
#values into integer values
print(a)

[[2. 3. 5. 6. 5. 0.]
 [4. 1. 4. 9. 7. 3.]
 [0. 7. 3. 9. 7. 8.]
 [5. 7. 6. 9. 2. 8.]
 [5. 1. 7. 5. 4. 3.]]


In [14]:
a[2,2] #to get a particular element from a matrix
a[3,:] #to get a particular row
a[:,5] #to get a particular coloumn

array([0., 3., 8., 8., 3.])

In [15]:
a.T #to transpose a matrix
a[1:3,2:4] #to get a submatrix

array([[4., 9.],
       [3., 9.]])

In [16]:
import numpy.linalg as la #widely used for solving problems in linear algebra
la.inv(np.random.rand(3,3))

array([[ 0.59540648, -1.76084723,  4.95226256],
       [-2.00378455,  3.41341999, -1.96599138],
       [ 3.43683145, -3.01119736, -1.05781505]])

In [17]:
a

array([[2., 3., 5., 6., 5., 0.],
       [4., 1., 4., 9., 7., 3.],
       [0., 7., 3., 9., 7., 8.],
       [5., 7., 6., 9., 2., 8.],
       [5., 1., 7., 5., 4., 3.]])

In [18]:
a.sort(axis=1) #sorting in ascending order of all coloumns
print(a)

[[0. 2. 3. 5. 5. 6.]
 [1. 3. 4. 4. 7. 9.]
 [0. 3. 7. 7. 8. 9.]
 [2. 5. 6. 7. 8. 9.]
 [1. 3. 4. 5. 5. 7.]]


In [19]:
a.sort(axis=0) #sort by row
a

array([[0., 2., 3., 4., 5., 6.],
       [0., 3., 4., 5., 5., 7.],
       [1., 3., 4., 5., 7., 9.],
       [1., 3., 6., 7., 8., 9.],
       [2., 5., 7., 7., 8., 9.]])

In [23]:
a=np.arange(50)
b=a[[3,8,9]] #it gives a array
b[1]=10 #if we change a element in b then this will not create a effect on a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [27]:
b=a[a>30] 
#a boolean array in numpy is contained by boolean values
bool_arr=(a%2==0)
print(bool_arr) #this gives a boolean array

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False]


In [30]:
b=a[(a>22) & (a<33)]
b

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [33]:
a=np.round(10*(np.random.rand(2,3)))
a

array([[4., 7., 3.],
       [8., 5., 8.]])

In [34]:
a+4 #this is called broadcasting

array([[ 8., 11.,  7.],
       [12.,  9., 12.]])

In [39]:
a+(np.arange(2).reshape(2,1))

array([[4., 7., 3.],
       [9., 6., 9.]])

In [41]:
b=np.round(10*(np.random.rand(2,2)))
b

array([[2., 7.],
       [1., 5.]])

In [42]:
a

array([[4., 7., 3.],
       [8., 5., 8.]])

In [44]:
c=np.hstack((a,b)) #the vstack function concatenate the two array
#horizontally
c

array([[4., 7., 3., 2., 7.],
       [8., 5., 8., 1., 5.]])

In [49]:
a=np.random.permutation(np.arange(10))
a.sort() #this sort function will sort the array in ascending order
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.sort(a) #another way to sort

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
#for sorting in descending order
a.sort()
b=a[::-1]
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [54]:
b=np.random.rand(1000000)
%timeit sum(b)
%timeit np.sum(b) #the numpy package is faster than anything in python

178 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.38 ms ± 12 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
